Repository kakao-tech-campus-2nd-step3/Team15_BE, pull requests merged in 2024-09, with the labels that each got.

#2 [FEAT] 로그 설정 및 회원, 챌린지 엔티티 구현
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/kakao/rebit/RebitApplication.java
  src/main/java/kakao/rebit/challenge/entity/Challenge.java
  src/main/java/kakao/rebit/challenge/entity/ChallengeParticipant.java
  src/main/java/kakao/rebit/challenge/entity/ChallengeType.java
  src/main/java/kakao/rebit/challenge/entity/HeadcountLimit.java
  src/main/java/kakao/rebit/challenge/entity/Period.java
  src/main/java/kakao/rebit/challenge/repository/ChallengeParticipantRepository.java
  src/main/java/kakao/rebit/challenge/repository/ChallengeRepository.java
  src/main/java/kakao/rebit/common/persistence/BaseEntity.java
  src/main/java/kakao/rebit/member/entity/Member.java
  src/main/java/kakao/rebit/member/entity/Role.java
  src/main/java/kakao/rebit/member/repository/MemberRepository.java
  src/main/java/kakao/rebit/utils/p6spy/P6SpyConfig.java
  src/main/java/kakao/rebit/utils/p6spy/P6SpyEventListener.java
  src/main/java/kakao/rebit/utils/p6spy/P6SpyFormatter.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: enhancement

#6 [FEAT] 피드, 좋아요 엔티티 구현
  src/main/java/kakao/rebit/Likes/entity/Likes.java
  src/main/java/kakao/rebit/Likes/repository/LikesRepository.java
  src/main/java/kakao/rebit/feed/entity/FavoriteBook.java
  src/main/java/kakao/rebit/feed/entity/Feed.java
  src/main/java/kakao/rebit/feed/entity/Magazine.java
  src/main/java/kakao/rebit/feed/entity/Story.java
  src/main/java/kakao/rebit/feed/repository/FavoriteBookRepository.java
  src/main/java/kakao/rebit/feed/repository/FeedRepository.java
  src/main/java/kakao/rebit/feed/repository/MagazineRepository.java
  src/main/java/kakao/rebit/feed/repository/StoryRepository.java
Labels: enhancement

#20 [FEAT] 챌린지 조회, 생성, 삭제 구현
  src/main/java/kakao/rebit/challenge/controller/ChallengeController.java
  src/main/java/kakao/rebit/challenge/dto/ChallengeRequest.java
  src/main/java/kakao/rebit/challenge/dto/ChallengeResponse.java
  src/main/java/kakao/rebit/challenge/dto/CreatorResponse.java
  src/main/java/kakao/rebit/challenge/service/ChallengeService.java
  src/main/java/kakao/rebit/member/dto/MemberResponse.java
  src/main/java/kakao/rebit/member/entity/Member.java
  src/main/java/kakao/rebit/member/service/MemberService.java
Labels: bug, enhancement

#24 [FEAT] 피드 조회 구현
  src/main/java/kakao/rebit/book/entity/Book.java
  src/main/java/kakao/rebit/feed/controller/FavoriteBookController.java
  src/main/java/kakao/rebit/feed/controller/FeedController.java
  src/main/java/kakao/rebit/feed/controller/MagazineController.java
  src/main/java/kakao/rebit/feed/controller/StoryController.java
  src/main/java/kakao/rebit/feed/dto/response/AuthorResponse.java
  src/main/java/kakao/rebit/feed/dto/response/BookResponse.java
  src/main/java/kakao/rebit/feed/dto/response/FavoriteBookResponse.java
  src/main/java/kakao/rebit/feed/dto/response/FeedResponse.java
  src/main/java/kakao/rebit/feed/dto/response/MagazineResponse.java
  src/main/java/kakao/rebit/feed/dto/response/StoryResponse.java
  src/main/java/kakao/rebit/feed/entity/Feed.java
  src/main/java/kakao/rebit/feed/entity/Magazine.java
  src/main/java/kakao/rebit/feed/repository/FavoriteBookRepository.java
  src/main/java/kakao/rebit/feed/repository/FeedRepository.java
  src/main/java/kakao/rebit/feed/repository/LikesRepository.java
  src/main/java/kakao/rebit/feed/repository/MagazineRepository.java
  src/main/java/kakao/rebit/feed/repository/StoryRepository.java
  src/main/java/kakao/rebit/feed/service/FavoriteBookService.java
  src/main/java/kakao/rebit/feed/service/FeedService.java
  src/main/java/kakao/rebit/feed/service/MagazineService.java
  src/main/java/kakao/rebit/feed/service/StoryService.java
Labels: enhancement

#44 [FEAT] CI/CD 설정
  .github/dev-deploy.yml
  Dockerfile
  src/main/resources/application.yml
Labels: enhancement

#46 [FIX] Github Actions 실행을 위해 파일 위치 변경
  .github/workflows/dev-deploy.yml
Labels: bug

#48 [CHORE] 서버 로그 설정
  src/main/resources/application.yml
Labels: enhancement
