Repository kakao-tech-campus-2nd-step3/Team15_BE, pull requests merged in 2024-11, with the labels that each got.

#109 [REFACTOR] 사용자 프로필 이미지 업로드 이벤트로 처리하도록 수정
  src/main/java/kakao/rebit/RebitApplication.java
  src/main/java/kakao/rebit/auth/controller/KakaoAuthController.java
  src/main/java/kakao/rebit/auth/event/ProfileImageUploadEventHandler.java
  src/main/java/kakao/rebit/auth/event/RegisteredEvent.java
  src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
  src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
  src/main/java/kakao/rebit/feed/service/FavoriteBookService.java
  src/main/java/kakao/rebit/s3/dto/S3UploadKeyRequest.java
Labels: enhancement

#110 [TEST] TestFixture 설정 및 챌린지 참여 테스트코드 작성
  build.gradle
  src/main/java/kakao/rebit/RebitApplication.java
  src/main/java/kakao/rebit/common/config/JpaAuditingConfig.java
  src/test/java/kakao/rebit/challenge/entity/ChallengeParticipationTest.java
  src/test/java/kakao/rebit/common/annotation/RepositoryTest.java
  src/test/resources/application-test.yml
  src/testFixtures/java/kakao/rebit/challenge/fixture/ChallengeFixture.java
  src/testFixtures/java/kakao/rebit/challenge/fixture/TestPeriod.java
  src/testFixtures/java/kakao/rebit/challenge/fixture/values/ChallengeDefaultValues.java
  src/testFixtures/java/kakao/rebit/member/fixture/MemberFixture.java
  src/testFixtures/java/kakao/rebit/member/fixture/values/MemberDefaultValues.java
Labels: enhancement

#117 [REFACTOR] 레디스 의존성 추가 및 KakaoAuthService 리펙토링
  build.gradle
  src/main/java/kakao/rebit/auth/controller/KakaoAuthController.java
  src/main/java/kakao/rebit/auth/jwt/TokenBlacklistRepository.java
  src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
Labels: bug

#121 [FEAT] 로그인한 사용자가 각 피드에 대해 좋아요를 눌렀는지 여부를 확인하는 기능 추가
  src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
  src/main/java/kakao/rebit/common/config/WebConfig.java
  src/main/java/kakao/rebit/feed/controller/FavoriteBookController.java
  src/main/java/kakao/rebit/feed/controller/FeedController.java
  src/main/java/kakao/rebit/feed/controller/MagazineController.java
  src/main/java/kakao/rebit/feed/controller/StoryController.java
  src/main/java/kakao/rebit/feed/dto/response/FavoriteBookResponse.java
  src/main/java/kakao/rebit/feed/dto/response/FeedResponse.java
  src/main/java/kakao/rebit/feed/dto/response/MagazineResponse.java
  src/main/java/kakao/rebit/feed/dto/response/StoryResponse.java
  src/main/java/kakao/rebit/feed/entity/Likes.java
  src/main/java/kakao/rebit/feed/exception/feed/FeedErrorCode.java
  src/main/java/kakao/rebit/feed/exception/feed/InvalidFeedFormatException.java
  src/main/java/kakao/rebit/feed/mapper/FeedMapper.java
  src/main/java/kakao/rebit/feed/repository/LikesRepository.java
  src/main/java/kakao/rebit/feed/service/FavoriteBookService.java
  src/main/java/kakao/rebit/feed/service/FeedService.java
  src/main/java/kakao/rebit/feed/service/LikesService.java
  src/main/java/kakao/rebit/feed/service/MagazineService.java
  src/main/java/kakao/rebit/feed/service/StoryService.java
  src/main/java/kakao/rebit/member/annotation/MemberInfoIfPresent.java
  src/main/java/kakao/rebit/member/entity/Member.java
  src/main/java/kakao/rebit/member/resolver/MemberInfoArgumentResolver.java
  src/main/java/kakao/rebit/member/resolver/OptionalMemberResolver.java
  src/main/java/kakao/rebit/s3/dto/S3UploadKeyRequest.java
  src/main/java/kakao/rebit/s3/service/S3Service.java
Labels: enhancement

#125 [FEAT] 마이페이지 피드 조회 기능 구현
  src/main/java/kakao/rebit/feed/controller/StoryController.java
  src/main/java/kakao/rebit/feed/repository/FavoriteBookRepository.java
  src/main/java/kakao/rebit/feed/repository/FeedRepository.java
  src/main/java/kakao/rebit/feed/repository/MagazineRepository.java
  src/main/java/kakao/rebit/feed/repository/StoryRepository.java
  src/main/java/kakao/rebit/feed/service/FavoriteBookService.java
  src/main/java/kakao/rebit/feed/service/FeedService.java
  src/main/java/kakao/rebit/feed/service/MagazineService.java
  src/main/java/kakao/rebit/feed/service/StoryService.java
  src/main/java/kakao/rebit/member/annotation/MemberInfo.java
  src/main/java/kakao/rebit/member/controller/MemberController.java
  src/main/java/kakao/rebit/member/dto/MemberProfileResponse.java
  src/main/java/kakao/rebit/member/dto/MemberResponse.java
  src/main/java/kakao/rebit/member/entity/Member.java
  src/main/java/kakao/rebit/member/resolver/OptionalMemberResolver.java
  src/main/java/kakao/rebit/member/service/MemberService.java
Labels: enhancement

#128 [TEST] 피드 테스트 코드 작성
  src/test/java/kakao/rebit/feed/entity/CommonFeedTest.java
  src/test/java/kakao/rebit/feed/entity/FavoriteBookTest.java
  src/test/java/kakao/rebit/feed/entity/MagazineTest.java
  src/test/java/kakao/rebit/feed/entity/StoryTest.java
  src/testFixtures/java/kakao/rebit/book/fixture/BookFixture.java
  src/testFixtures/java/kakao/rebit/book/fixture/values/BookDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/FeedFixture.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/FavoriteBookDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/MagazineDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/StoryDefaultValues.java
  src/testFixtures/java/kakao/rebit/member/fixture/MemberFixture.java
Labels: enhancement

#131 [TEST] 챌린지 참여 및 인증글 서비스 테스트 코드 작성
  src/main/java/kakao/rebit/auth/jwt/JwtInterceptor.java
  src/main/java/kakao/rebit/auth/token/AuthToken.java
  src/main/java/kakao/rebit/challenge/service/ChallengeVerificationService.java
  src/test/java/kakao/rebit/book/entity/BookServiceTest.java
  src/test/java/kakao/rebit/challenge/entity/ChallengeParticipationTest.java
  src/test/java/kakao/rebit/challenge/service/ChallengeParticipationServiceTest.java
  src/test/java/kakao/rebit/challenge/service/ChallengeVerificationServiceTest.java
  src/testFixtures/java/kakao/rebit/challenge/fixture/ChallengeParticipationFixture.java
  src/testFixtures/java/kakao/rebit/challenge/fixture/ChallengeVerificationFixture.java
  src/testFixtures/java/kakao/rebit/challenge/fixture/values/ChallengeVerificationDefaultValues.java
  src/testFixtures/java/kakao/rebit/member/fixture/MemberFixture.java
Labels: enhancement

#139 [REFACTOR] 요청 DTO의 ImageKey 검증하는 부분 수정
  src/main/java/kakao/rebit/feed/dto/request/create/CreateMagazineRequest.java
  src/main/java/kakao/rebit/feed/dto/request/create/CreateStoryRequest.java
  src/main/java/kakao/rebit/feed/dto/request/update/UpdateMagazineRequest.java
  src/main/java/kakao/rebit/feed/dto/request/update/UpdateStoryRequest.java
  src/main/java/kakao/rebit/member/controller/MemberController.java
  src/main/java/kakao/rebit/member/dto/MemberRequest.java
Labels: enhancement

#141 [TEST] 피드 서비스 테스트 코드 작성
  src/test/java/kakao/rebit/feed/service/FavoriteBookServiceTest.java
  src/test/java/kakao/rebit/feed/service/FeedServiceTest.java
  src/test/java/kakao/rebit/feed/service/MagazineServiceTest.java
  src/test/java/kakao/rebit/feed/service/StoryServiceTest.java
Labels: enhancement

#148 [TEST] E2E 테스트를 위한 외부 의존성 서비스 모킹
  build.gradle
  src/main/java/kakao/rebit/auth/controller/KakaoAuthController.java
  src/main/java/kakao/rebit/auth/service/KakaoApiClient.java
  src/main/java/kakao/rebit/book/service/AladinApiService.java
  src/main/java/kakao/rebit/challenge/controller/ChallengeParticipationController.java
  src/main/java/kakao/rebit/challenge/controller/ChallengeVerificationController.java
  src/main/java/kakao/rebit/challenge/repository/ChallengeParticipationRepository.java
  src/main/java/kakao/rebit/challenge/repository/ChallengeVerificationRepository.java
  src/main/java/kakao/rebit/challenge/service/ChallengeParticipationService.java
  src/main/java/kakao/rebit/challenge/service/ChallengeVerificationService.java
  src/main/resources/application.yml
  src/test/java/kakao/rebit/auth/fixture/TestKakaoAuthService.java
  src/test/java/kakao/rebit/auth/fixture/TestS3Service.java
  src/test/java/kakao/rebit/auth/util/TestAuthUtils.java
  src/test/java/kakao/rebit/challenge/e2e/ChallengeE2ETest.java
  src/test/java/kakao/rebit/config/TestConfig.java
  src/test/resources/application-test.yml
  src/testFixtures/java/kakao/rebit/challenge/fixture/ChallengeFixture.java
  src/testFixtures/java/kakao/rebit/challenge/fixture/values/ChallengeDefaultValues.java
Labels: enhancement

#152 [FEAT] 마이페이지 챌린지 조회
  src/main/java/kakao/rebit/challenge/repository/ChallengeParticipationRepository.java
  src/main/java/kakao/rebit/challenge/service/ChallengeParticipationService.java
  src/main/java/kakao/rebit/challenge/service/ChallengeService.java
  src/main/java/kakao/rebit/member/controller/MemberController.java
Labels: enhancement

#150 [TEST] 챌린지 E2E 테스트
  src/main/java/kakao/rebit/challenge/entity/ChallengeParticipation.java
  src/main/java/kakao/rebit/member/entity/Member.java
  src/main/resources/application.yml
  src/test/java/kakao/rebit/auth/fixture/TestKakaoAuthService.java
  src/test/java/kakao/rebit/auth/util/AuthApiTestClient.java
  src/test/java/kakao/rebit/auth/util/ChallengeApiTestClient.java
  src/test/java/kakao/rebit/auth/util/MemberApiTestClient.java
  src/test/java/kakao/rebit/auth/util/TestAuthUtils.java
  src/test/java/kakao/rebit/challenge/e2e/ChallengeE2ETest.java
  src/test/java/kakao/rebit/common/PageTemplate.java
  src/test/resources/application-test.yml
  src/testFixtures/java/kakao/rebit/challenge/fixture/ChallengeFixture.java
  src/testFixtures/java/kakao/rebit/member/fixture/MemberFixture.java
Labels: enhancement

#155 [FEAT] 게시글 내용 글자수 제한 늘림
  src/main/java/kakao/rebit/challenge/entity/ChallengeVerification.java
  src/main/java/kakao/rebit/feed/entity/FavoriteBook.java
  src/main/java/kakao/rebit/feed/entity/Magazine.java
  src/main/java/kakao/rebit/feed/entity/Story.java
  src/main/resources/application.yml
Labels: enhancement

#157 [TEST] 피드 E2E 테스트 작성
  src/main/java/kakao/rebit/auth/token/AuthToken.java
  src/main/java/kakao/rebit/feed/dto/request/create/CreateFavoriteBookRequest.java
  src/main/java/kakao/rebit/feed/dto/request/create/CreateFeedRequest.java
  src/main/java/kakao/rebit/feed/dto/request/create/CreateMagazineRequest.java
  src/main/java/kakao/rebit/feed/dto/request/create/CreateStoryRequest.java
  src/main/java/kakao/rebit/feed/dto/response/FavoriteBookResponse.java
  src/main/java/kakao/rebit/feed/dto/response/FeedResponse.java
  src/main/java/kakao/rebit/feed/dto/response/MagazineResponse.java
  src/main/java/kakao/rebit/feed/dto/response/StoryResponse.java
  src/test/java/kakao/rebit/auth/util/FeedApiTestClient.java
  src/test/java/kakao/rebit/common/PageTemplate.java
  src/test/java/kakao/rebit/feed/e2e/FavoriteBookE2ETest.java
  src/test/java/kakao/rebit/feed/e2e/FeedE2ETest.java
  src/test/java/kakao/rebit/feed/e2e/MagazineE2ETest.java
  src/test/java/kakao/rebit/feed/e2e/StoryE2ETest.java
  src/testFixtures/java/kakao/rebit/feed/fixture/FeedFixture.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/FavoriteBookDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/MagazineDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/StoryDefaultValues.java
Labels: enhancement

#159 [FEAT] 독서 일기 생성 일자 추가
  src/main/java/kakao/rebit/diary/dto/DiaryRequest.java
  src/main/java/kakao/rebit/diary/dto/DiaryResponse.java
  src/main/java/kakao/rebit/diary/entity/Diary.java
  src/main/java/kakao/rebit/diary/service/DiaryService.java
  src/main/java/kakao/rebit/member/controller/MemberController.java
Labels: enhancement

#162 [FEAT] 챌린지 현재 참여 인원 및 입장료 총합 반환
  src/main/java/kakao/rebit/challenge/dto/ChallengeResponse.java
  src/main/java/kakao/rebit/challenge/entity/Challenge.java
  src/main/java/kakao/rebit/challenge/service/ChallengeService.java
Labels: enhancement

#164 [FIX] 입장 인원이 없는 챌린지의 경우를 고려해 총 상금 쿼리 수정
  src/main/java/kakao/rebit/challenge/entity/Challenge.java
Labels: bug

#166 [FEAT] 챌린지 보상 분배 스케줄링 구현
  src/main/java/kakao/rebit/challenge/repository/ChallengeParticipationRepository.java
  src/main/java/kakao/rebit/challenge/repository/ChallengeRepository.java
  src/main/java/kakao/rebit/challenge/repository/ChallengeVerificationRepository.java
  src/main/java/kakao/rebit/challenge/scheduler/ChallengeRewardScheduler.java
  src/main/java/kakao/rebit/challenge/service/ChallengeRewardService.java
  src/main/java/kakao/rebit/common/config/WebConfig.java
Labels: enhancement

#168 [REFACTOR] 독서 일기 응답 필드 수정
  src/main/java/kakao/rebit/diary/dto/DiaryBookResponse.java
  src/main/java/kakao/rebit/diary/dto/DiaryResponse.java
  src/main/java/kakao/rebit/diary/service/DiaryService.java
Labels: enhancement

#169 [FEAT] 마이페이지 배경 이미지 추가
  src/main/java/kakao/rebit/auth/service/KakaoAuthService.java
  src/main/java/kakao/rebit/member/controller/MemberController.java
  src/main/java/kakao/rebit/member/dto/AdminMemberRequest.java
  src/main/java/kakao/rebit/member/dto/MemberProfileResponse.java
  src/main/java/kakao/rebit/member/dto/MemberRequest.java
  src/main/java/kakao/rebit/member/dto/MemberResponse.java
  src/main/java/kakao/rebit/member/entity/Member.java
  src/main/java/kakao/rebit/member/exception/MemberErrorCode.java
  src/main/java/kakao/rebit/member/exception/MemberNotFoundException.java
  src/main/java/kakao/rebit/member/mapper/MemberMapper.java
  src/main/java/kakao/rebit/member/service/MemberService.java
  src/main/java/kakao/rebit/s3/domain/S3Type.java
Labels: enhancement

#174 [REFACTOR] 테스트 클래스 DisplayName 적용 및 테스트 정상 동작하도록 수정
  src/main/java/kakao/rebit/feed/controller/MagazineController.java
  src/main/java/kakao/rebit/feed/dto/request/create/CreateMagazineRequest.java
  src/main/java/kakao/rebit/feed/dto/request/update/UpdateMagazineRequest.java
  src/main/java/kakao/rebit/feed/dto/response/MagazineResponse.java
  src/main/java/kakao/rebit/member/controller/MemberController.java
  src/test/java/kakao/rebit/book/service/BookServiceTest.java
  src/test/java/kakao/rebit/feed/e2e/MagazineE2ETest.java
  src/test/java/kakao/rebit/feed/entity/CommonFeedTest.java
  src/test/java/kakao/rebit/feed/entity/FavoriteBookTest.java
  src/test/java/kakao/rebit/feed/entity/MagazineTest.java
  src/test/java/kakao/rebit/feed/entity/StoryTest.java
  src/test/java/kakao/rebit/feed/service/FeedServiceTest.java
  src/test/java/kakao/rebit/feed/service/MagazineServiceTest.java
  src/testFixtures/java/kakao/rebit/member/fixture/MemberFixture.java
  src/testFixtures/java/kakao/rebit/member/fixture/values/MemberDefaultValues.java
Labels: bug, enhancement

#176 [FEAT] 챌린지 주최자는 생성과 동시에 챌린지에 참여
  src/main/java/kakao/rebit/challenge/service/ChallengeService.java
Labels: enhancement

#181 [CHORE] docker-compose.yml 파일 업로드
  docker-compose.yml
Labels: documentation, enhancement

#182 [REFACTOR] 독서 일기 년,월로 조회하도록 수정
  src/main/java/kakao/rebit/diary/controller/DiaryController.java
  src/main/java/kakao/rebit/diary/dto/DiaryRequest.java
  src/main/java/kakao/rebit/diary/dto/DiaryResponse.java
  src/main/java/kakao/rebit/diary/entity/Diary.java
  src/main/java/kakao/rebit/diary/repository/DiaryRepository.java
  src/main/java/kakao/rebit/diary/service/DiaryService.java
  src/main/resources/application.yml
  src/test/java/kakao/rebit/auth/util/DiaryApiTestClient.java
  src/test/java/kakao/rebit/diary/e2e/DiaryE2ETest.java
  src/test/java/kakao/rebit/diary/entity/DiaryTest.java
  src/test/java/kakao/rebit/diary/service/DiaryServiceTest.java
  src/testFixtures/java/kakao/rebit/diary/fixture/DiaryFixture.java
  src/testFixtures/java/kakao/rebit/diary/fixture/values/DiaryDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/FavoriteBookDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/MagazineDefaultValues.java
  src/testFixtures/java/kakao/rebit/feed/fixture/values/StoryDefaultValues.java
Labels: enhancement

#184 [FIX] 다이어리 엔티티 Book 외래키 컬럼명 수정
  src/main/java/kakao/rebit/diary/controller/DiaryController.java
  src/main/java/kakao/rebit/diary/entity/Diary.java
Labels: enhancement
